version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Adjust if necessary
  build:
    commands:
      - echo "Triggering PowerShell script on EC2 instance"
      - |
        # Specify the EC2 instance ID
        $INSTANCE_ID = "i-0364c315bbb057ef2"  # Replace with your EC2 instance ID
        
        # Run the AWS SSM send-command to trigger the PowerShell commands directly on EC2 instance
        aws ssm send-command `
          --instance-ids $INSTANCE_ID `
          --document-name "AWS-RunPowerShellScript" `
          --parameters "commands=[
            'if (Test-Path \"C:\\Users\\Administrator\\Desktop\\Docusign_sample\") { Remove-Item -Recurse -Force \"C:\\Users\\Administrator\\Desktop\\Docusign_sample\" }',
            'git clone https://github.com/ThanviAlampur/Docusign_sample.git \"C:\\Users\\Administrator\\Desktop\\Docusign_sample\"',
            'python.exe -m pip install --upgrade pip',
            'pip install -r C:\\Users\\Administrator\\Desktop\\Docusign_sample\\requirements.txt',
            'pip install --upgrade numpy pandas',
            'pip install python-docx',
            'pip install webdriver-manager',
            'pip install selenium',
            'pip install pillow',
            'pytest C:\\Users\\Administrator\\Desktop\\Docusign_sample\\tests\\test_change_sign_tag_size.py -v -s'
          ]"

  post_build:
    commands:
      - echo "Script triggered successfully on EC2 instance"
