version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Triggering PowerShell script on EC2 instance"
      - |
        # Specify the EC2 instance ID
        INSTANCE_ID="i-0364c315bbb057ef2"  # Replace with your EC2 instance ID
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunPowerShellScript" \
          --parameters 'commands=["powershell.exe -ExecutionPolicy Bypass -File C:\\Users\\Administrator\\Desktop\\run_tests.ps1"]'
